# Shared mechanics of file-writing renderers: the provenance line, the
# exists-guard (deployed migrations are checksummed and must never be
# rewritten; identical SUPPLIER FACTS -> skip, divergence -> error), the
# SELECT 1/0 fuse headers and the versioned-file writing loop.

from collections.abc import Sequence
from pathlib import Path

from ddldelta.errors import GenerationError
from ddldelta.plan import MigrationPlan
from ddldelta.render.sql import statement

# Lines starting with this prefix are meta framing, not supplier facts.
META_PREFIX = '"_'

PROVENANCE_TEMPLATE = (
    "-- generated by {generated_by} ({comparison}); do not edit manually")

CRITICAL_FILE_HEADER = (
    'SELECT 1/0 AS "CRITICAL CHANGES DETECTED - PLEASE REVIEW THIS FILE!";')
CRITICAL_SUMMARY_HEADER = (
    'SELECT 1/0 AS "CRITICAL CHANGES DETECTED - PLEASE REVIEW THE LISTED FILES!";')


def provenance(comparison: str, generated_by: str, template: str = PROVENANCE_TEMPLATE) -> str:
    return template.format(generated_by=generated_by, comparison=comparison)


def _contained(target_dir: Path, name: str) -> Path:
    """Resolves `name` against target_dir, refusing a path that escapes it.
    Table names and delivery labels are supplier/vendor-controlled
    identifiers (a delivered DDL file can name a table "../../evil" and
    parse fine), so a constructed migration filename is not trusted input
    by construction."""
    target = (target_dir / name).resolve()
    if not target.is_relative_to(target_dir.resolve()):
        raise GenerationError(
            f"table or label produces a file name escaping the target "
            f"directory {target_dir} - refusing to write: {name!r}")
    return target


def _provenance_prefix(template: str) -> str:
    """The static lead of the template - what the facts filter matches."""
    prefix = template.split("{", 1)[0].rstrip()
    if not prefix:
        raise GenerationError(
            "provenance template needs a static, non-empty lead before the "
            "first placeholder - an empty prefix would match every line")
    return prefix


def _facts(text: str, meta_prefix: str, provenance_prefix: str) -> str:
    """The comparable part of a generated file: without the leading
    provenance line (always line 0 in generated files - anchoring there
    keeps a short prefix like '--' from swallowing commented statements)
    and without meta-column definitions. The meta framing may evolve -
    deployed files then stay untouched; diverging supplier facts abort."""
    lines = text.splitlines()
    if lines and lines[0].strip().startswith(provenance_prefix):
        lines = lines[1:]
    return "\n".join(
        line for line in lines if not line.strip().startswith(meta_prefix))


def write_generated(target: Path, content: str, meta_prefix: str = META_PREFIX,
                    provenance_template: str = PROVENANCE_TEMPLATE) -> bool:
    """Writes a generated migration with an exists-guard; True if written.

    Identical supplier facts -> skip (reruns stay no-ops even when the meta
    framing evolved). Diverging facts raise: deployed migrations are
    checksummed by schemachange and must never be rewritten.
    """
    prefix = _provenance_prefix(provenance_template)
    if target.exists():
        existing = target.read_text(encoding="utf-8")
        if _facts(existing, meta_prefix, prefix) == _facts(content, meta_prefix, prefix):
            return False
        raise GenerationError(
            f"{target} exists with diverging content - deployed migrations "
            "must never be rewritten (schemachange checksum). Resolve the "
            "divergence.")
    target.write_text(content, encoding="utf-8")
    return True


def write_plan(plan: MigrationPlan, target_dir: Path, generated_by: str,
               meta_ddl: Sequence[str] = (),
               meta_prefix: str = META_PREFIX, provenance_template: str = PROVENANCE_TEMPLATE,
               file_header: str = CRITICAL_FILE_HEADER,
               summary_header: str = CRITICAL_SUMMARY_HEADER) -> tuple[Path, ...]:
    """Writes one V<label>.<NNNN>__<table>.sql per planned table (critical:
    statements as comments behind the fuse) plus the .0000 critical summary;
    returns the paths actually written (guard skips excluded)."""
    target_dir.mkdir(parents=True, exist_ok=True)
    head = provenance(plan.comparison, generated_by, provenance_template)
    written: list[Path] = []
    counter = 1
    critical_names: list[str] = []
    for table_plan in plan.tables:
        target = _contained(target_dir, f"V{plan.label}.{counter:04d}__{table_plan.table}.sql")
        counter += 1
        statements = [statement(c, meta_ddl) for c in table_plan.changes]
        if table_plan.critical:
            critical_names.append(target.name)
            lines = [head, file_header] + [f"-- {s}" for s in statements]
        else:
            lines = [head] + statements
        if write_generated(target, "\n".join(lines) + "\n",
                           meta_prefix=meta_prefix,
                           provenance_template=provenance_template):
            written.append(target)
    if critical_names:
        summary = _contained(target_dir, f"V{plan.label}.0000__CRITICAL_CHANGES.sql")
        lines = [head, summary_header] + [f"-- {n}" for n in critical_names]
        if write_generated(summary, "\n".join(lines) + "\n",
                           meta_prefix=meta_prefix,
                           provenance_template=provenance_template):
            written.append(summary)
    return tuple(written)
