# Generates schemachange migrations from the n vs n-1 DDL comparison -
# now the ORCHESTRATION over the generalized parts: DeliveryDirectorySource
# -> model (optionally without_nullability) -> build_plan(FusePolicy) ->
# SchemachangeRenderer. Everything repo-specific stays injected via
# GeneratorConfig; the module never logs and never exits (GenerationError).
# The three cases per table and the never-overwrite guard are documented at
# their new homes: policy.py, render/files.py.
# generate_supplier is the schemachange-specific convenience orchestration;
# other outputs (report, Flyway) compose sources -> build_plan -> renderer
# directly.
# Note: source.load() parses deliveries BEFORE the config yml is created -
# an unparseable first delivery leaves no yml behind (deliberate change vs.
# the legacy order).

from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from textwrap import dedent

from ddldelta.change_history import change_history_table
from ddldelta.ddl_parser import parser_for
from ddldelta.errors import GenerationError
from ddldelta.model import without_nullability
from ddldelta.plan import build_plan
from ddldelta.policy import ChangePolicy, FusePolicy
from ddldelta.render.files import (
    CRITICAL_FILE_HEADER,
    CRITICAL_SUMMARY_HEADER,
    META_PREFIX,
    PROVENANCE_TEMPLATE,
    provenance,
    write_generated,
)
from ddldelta.render.schemachange import SchemachangeRenderer
from ddldelta.sources import DeliveryDirectorySource

__all__ = [  # re-exports: consumers keep importing these from generator
    "CRITICAL_FILE_HEADER", "CRITICAL_SUMMARY_HEADER", "GenerationError",
    "GeneratorConfig", "SupplierConfig", "SupplierResult",
    "generate_supplier", "provenance",
    "schemachange_config", "write_generated",
]


@dataclass(frozen=True)
class SupplierConfig:
    dialect: str          # sqlglot dialect name (ddl_parser.DIALECTS)
    landing_schema: str   # rendered as snowflake-schema into the yml


@dataclass(frozen=True)
class GeneratorConfig:
    ddl_dir: Path                # <ddl_dir>/<supplier>/<delivery>/*.sql
    schemachange_dir: Path       # <schemachange_dir>/<supplier>/V*.sql + yml
    repo_root: Path              # yml root-folder is rendered relative to this
    account: str                 # the six Snowflake values are text rendered
    user: str                    # into the yml only, never used to connect
    role: str
    warehouse: str
    database: str
    metadata_schema: str
    suppliers: Mapping[str, SupplierConfig]
    meta_ddl: tuple[str, ...]    # trailing meta-column DDL lines for CREATE TABLE
    generated_by: str            # provenance line + yml header comment
    meta_prefix: str = META_PREFIX
    provenance_template: str = PROVENANCE_TEMPLATE
    # False: nullability is stripped from the model (model.without_nullability)
    # before diffing - no NOT NULL reaches the target, nullability-only
    # changes vanish. CAUTION: flipping changes the supplier facts of
    # regenerated files; flip only together with a rebuild.
    enforce_not_null: bool = True
    policy: ChangePolicy = field(default_factory=FusePolicy)


@dataclass(frozen=True)
class SupplierResult:
    delivery: str | None            # None: supplier dir holds no deliveries
    comparison: str | None          # "<previous|(initial)> -> <current>"
    config_created: Path | None     # schemachange-config.yml, if newly written
    written: tuple[Path, ...]       # migrations actually written (guard skips excluded)


def schemachange_config(config: GeneratorConfig, supplier: str) -> str:
    # root-folder is rendered repo-root-relative: schemachange runs with
    # CWD = repo root (the consumer pins cwd), and the YAML must not contain
    # machine-specific absolute paths.
    root = (config.schemachange_dir / supplier).relative_to(config.repo_root).as_posix()
    return dedent(f"""\
        # Generated by {config.generated_by} (only when missing - edits here stick).
        # schemachange configuration for the {supplier} import (dev). Run from the repo root:
        #   uv run schemachange deploy --config-folder {root}
        # NEVER with --create-change-history-table - deploys create no infrastructure;
        # the history table is a one-time manual bootstrap per supplier
        # (tools/bootstrap_metadata.py).
        # Auth deliberately comes from the environment, not from this file: run.py sets
        # SNOWFLAKE_PASSWORD from SNOWFLAKE_ACCESS_TOKEN (PAT, default authenticator)
        # or, without a token, SNOWFLAKE_AUTHENTICATOR=externalbrowser (SSO fallback).
        config-version: 1
        root-folder: {root}
        change-history-table: {config.database}.{config.metadata_schema}.{change_history_table(supplier)}
        snowflake-account: {config.account}
        snowflake-user: {config.user}
        snowflake-role: {config.role}
        snowflake-warehouse: {config.warehouse}
        snowflake-database: {config.database}
        snowflake-schema: {config.suppliers[supplier].landing_schema}
        query-tag: {supplier}-schemachange
        """)


def generate_supplier(config: GeneratorConfig, supplier: str) -> SupplierResult:
    """Generates one supplier's migrations for its latest delivery.

    Idempotent per delivery via the exists-guard; returns what happened
    for the caller to report.
    """
    supplier_config = config.suppliers[supplier]
    source = DeliveryDirectorySource(
        config.ddl_dir / supplier, parser_for(supplier_config.dialect))
    pair = source.load()
    if pair is None:
        return SupplierResult(None, None, None, ())
    target_dir = config.schemachange_dir / supplier
    target_dir.mkdir(parents=True, exist_ok=True)
    yml, config_created = target_dir / "schemachange-config.yml", None
    if not yml.exists():
        yml.write_text(schemachange_config(config, supplier), encoding="utf-8")
        config_created = yml

    old, new = pair.old, pair.new
    if not config.enforce_not_null:
        old, new = without_nullability(old), without_nullability(new)
    plan = build_plan(pair.new_label, pair.comparison, old, new, config.policy)
    renderer = SchemachangeRenderer(
        target_dir=target_dir, generated_by=config.generated_by,
        meta_ddl=config.meta_ddl, meta_prefix=config.meta_prefix,
        provenance_template=config.provenance_template)
    return SupplierResult(pair.new_label, pair.comparison, config_created,
                          renderer.render(plan))
