import pytest

from ddldelta.generator import (
    CRITICAL_FILE_HEADER,
    CRITICAL_SUMMARY_HEADER,
    GenerationError,
    GeneratorConfig,
    SupplierConfig,
    generate_supplier,
    schemachange_config,
)
from ddldelta.policy import Severity

# Meta-Stand-in: der echte Block wird vom Consumer injiziert (dort
# historization.meta_ddl()); fuer die Mechanik reichen zwei Zeilen.
META = ('"_DELIVERY" VARCHAR', '"_VALID_FROM" DATE')


def config_for(tmp_path, **overrides):
    values = dict(
        ddl_dir=tmp_path / "ddl",
        schemachange_dir=tmp_path / "schemachange",
        repo_root=tmp_path,
        account="acc", user="usr", role="rl", warehouse="wh",
        database="DB", metadata_schema="METADATA",
        suppliers={"haynespro": SupplierConfig("tsql", "HAYNESPRO_LANDING")},
        meta_ddl=META,
        generated_by="test.generator",
        provenance_template="-- generiert von {generated_by} ({comparison}); nicht manuell aendern",
    )
    values.update(overrides)
    return GeneratorConfig(**values)


def test_generate_supplier_reicht_enforce_not_null_durch(tmp_path):
    config = config_for(tmp_path, enforce_not_null=False)
    delivery = tmp_path / "ddl" / "haynespro" / "2026Q3"
    delivery.mkdir(parents=True)
    (delivery / "dbo_NEU.sql").write_text(
        "CREATE TABLE [dbo].[NEU](\n    [id] [int] NOT NULL\n)", encoding="utf-8")
    result = generate_supplier(config, "haynespro")
    content = result.written[0].read_text(encoding="utf-8")
    assert '"id" INT,' in content and "NOT NULL" not in content


# ---- schemachange_config -----------------------------------------------------

def test_config_ohne_eingerueckte_zeilen_und_mit_injizierten_werten(tmp_path):
    config = schemachange_config(
        config_for(tmp_path, schemachange_dir=tmp_path / "src" / "schemachange"),
        "haynespro")
    lines = config.splitlines()
    assert all(not line.startswith(" ") for line in lines if line)
    assert "# #" not in config
    assert "change-history-table: DB.METADATA.SCHEMACHANGE_CHANGE_HISTORY_HAYNESPRO" in config
    assert "root-folder: src/schemachange/haynespro" in config
    assert "snowflake-schema: HAYNESPRO_LANDING" in config
    assert "# Generated by test.generator" in config


# ---- generate_supplier (end-to-end) --------------------------------------------

NEW_STABIL = "CREATE TABLE [dbo].[STABIL](\n    [id] [int] NOT NULL\n)"
NEW_TABLE = "CREATE TABLE [dbo].[NEU](\n    [id] [int] NOT NULL,\n    [name] [nvarchar](50) NULL\n)"


def test_emission_faelle_und_fuse(tmp_path):
    config = config_for(tmp_path)
    old = tmp_path / "ddl" / "haynespro" / "2026Q2"
    new = tmp_path / "ddl" / "haynespro" / "2026Q3"
    old.mkdir(parents=True)
    new.mkdir(parents=True)
    (old / "dbo_STABIL.sql").write_text(NEW_STABIL, encoding="utf-8")
    (old / "dbo_FAELLT_WEG.sql").write_text(
        "CREATE TABLE [dbo].[FAELLT_WEG](\n    [id] [int] NOT NULL\n)", encoding="utf-8")
    (new / "dbo_STABIL.sql").write_text(NEW_STABIL, encoding="utf-8")
    (new / "dbo_NEU.sql").write_text(NEW_TABLE, encoding="utf-8")

    result = generate_supplier(config, "haynespro")

    out = tmp_path / "schemachange" / "haynespro"
    assert result.delivery == "2026Q3"
    assert result.comparison == "2026Q2 -> 2026Q3"
    assert result.config_created == out / "schemachange-config.yml"
    names = sorted(p.name for p in out.glob("*.sql"))
    # FAELLT_WEG (kritisch) vor NEU (Fall 2); STABIL unveraendert -> keine Datei
    assert names == [
        "V2026Q3.0000__CRITICAL_CHANGES.sql",
        "V2026Q3.0001__FAELLT_WEG.sql",
        "V2026Q3.0002__NEU.sql",
    ]
    assert sorted(p.name for p in result.written) == names
    critical = (out / "V2026Q3.0001__FAELLT_WEG.sql").read_text(encoding="utf-8")
    lines = critical.splitlines()
    assert lines[0].startswith("-- generiert von")   # Provenienz zuerst
    assert lines[1] == CRITICAL_FILE_HEADER          # dann die Fuse
    assert lines[2] == '-- DROP TABLE "FAELLT_WEG";'
    new_file = (out / "V2026Q3.0002__NEU.sql").read_text(encoding="utf-8")
    assert new_file.splitlines()[0].startswith(
        "-- generiert von test.generator (2026Q2 -> 2026Q3)")
    assert 'CREATE TABLE "NEU"' in new_file
    summary = (out / "V2026Q3.0000__CRITICAL_CHANGES.sql").read_text(encoding="utf-8")
    assert CRITICAL_SUMMARY_HEADER in summary
    assert "V2026Q3.0001__FAELLT_WEG.sql" in summary
    config_text = (out / "schemachange-config.yml").read_text(encoding="utf-8")
    assert "root-folder: schemachange/haynespro" in config_text

    # Wiederholungslauf: alles identisch -> keine Aenderung, kein Abbruch
    before = {p.name: p.read_text(encoding="utf-8") for p in out.glob("*.sql")}
    rerun = generate_supplier(config, "haynespro")
    after = {p.name: p.read_text(encoding="utf-8") for p in out.glob("*.sql")}
    assert after == before
    assert rerun.written == ()
    assert rerun.config_created is None


def test_lieferant_ohne_lieferungen_liefert_leeres_ergebnis(tmp_path):
    (tmp_path / "ddl" / "haynespro").mkdir(parents=True)
    result = generate_supplier(config_for(tmp_path), "haynespro")
    assert result == type(result)(None, None, None, ())


def test_unparsebare_ddl_wirft_generation_error_mit_dateiname(tmp_path):
    delivery = tmp_path / "ddl" / "haynespro" / "2026Q3"
    delivery.mkdir(parents=True)
    (delivery / "kaputt.sql").write_text("PRINT 'kein create table'", encoding="utf-8")
    with pytest.raises(GenerationError, match="kaputt.sql"):
        generate_supplier(config_for(tmp_path), "haynespro")


def test_eigene_policy_schaltet_fuse_ab(tmp_path):
    class AllowEverything:
        def classify(self, change):
            return Severity.SAFE

    config = config_for(tmp_path, policy=AllowEverything())
    old = tmp_path / "ddl" / "haynespro" / "2026Q2"
    new = tmp_path / "ddl" / "haynespro" / "2026Q3"
    old.mkdir(parents=True)
    new.mkdir(parents=True)
    (old / "dbo_WEG.sql").write_text(
        "CREATE TABLE [dbo].[WEG](\n    [id] [int] NOT NULL\n)", encoding="utf-8")
    result = generate_supplier(config, "haynespro")
    content = result.written[0].read_text(encoding="utf-8")
    assert 'DROP TABLE "WEG";' in content
    assert "SELECT 1/0" not in content          # keine Fuse
    assert "-- DROP" not in content             # Statement ausfuehrbar, nicht kommentiert
    assert not [p for p in result.written if "CRITICAL_CHANGES" in p.name]
