import json

from ddldelta.cli import main
from ddldelta.snapshot import load_snapshot, save_snapshot
from ddldelta.model import table_from


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


# ---- check ------------------------------------------------------------------

def test_check_kompatible_aenderung_gibt_0_zurueck(tmp_path, capsys):
    old = tmp_path / "old"
    new = tmp_path / "new"
    write(old / "a.sql", "CREATE TABLE a (id int)")
    write(new / "a.sql", "CREATE TABLE a (id int, neu int)")

    code = main(["check", "--dialect", "mysql", str(old), str(new)])

    assert code == 0
    out = capsys.readouterr().out
    assert "old -> new" in out


def test_check_kritische_aenderung_gibt_1_zurueck_mit_json(tmp_path, capsys):
    old = tmp_path / "old"
    new = tmp_path / "new"
    write(old / "a.sql", "CREATE TABLE a (id int)")
    write(new / "b.sql", "CREATE TABLE b (id int)")

    code = main(["check", "--dialect", "mysql", str(old), str(new), "--json"])

    assert code == 1
    data = json.loads(capsys.readouterr().out)
    assert data["compatible"] is False


def test_check_mit_json_snapshot_als_old_nutzt_gespeichertes_label(tmp_path, capsys):
    old_schema = {"a": table_from("a", {"id": ("INT", True)})}
    snapshot_path = tmp_path / "snapshot.json"
    save_snapshot(snapshot_path, old_schema, "2026Q2")
    new = tmp_path / "new"
    write(new / "a.sql", "CREATE TABLE a (id int not null, neu int)")

    code = main(["check", "--dialect", "mysql", str(snapshot_path), str(new)])

    assert code == 0
    out = capsys.readouterr().out
    assert "2026Q2 -> new" in out


# ---- generate -----------------------------------------------------------------

def test_generate_initial_schreibt_migration_mit_englischer_provenienzzeile(tmp_path, capsys):
    new = tmp_path / "new"
    write(new / "a.sql", "CREATE TABLE a (id int)")
    out_dir = tmp_path / "out"

    code = main(["generate", "--dialect", "mysql", "--label", "2026Q3",
                "--out", str(out_dir), str(new)])

    assert code == 0
    files = sorted(out_dir.glob("V2026Q3.*__a.sql"))
    assert len(files) == 1
    content = files[0].read_text(encoding="utf-8")
    assert content.startswith(
        "-- generated by ddldelta ((initial) -> 2026Q3); do not edit manually")


def test_generate_mit_snapshot_speichert_und_zweiter_lauf_ist_leer(tmp_path, capsys):
    new = tmp_path / "new"
    write(new / "a.sql", "CREATE TABLE a (id int)")
    out_dir = tmp_path / "out"
    snapshot_path = tmp_path / "snapshot.json"

    code = main(["generate", "--dialect", "mysql", "--label", "2026Q3",
                "--out", str(out_dir), str(new), "--snapshot", str(snapshot_path)])
    assert code == 0
    assert snapshot_path.exists()
    label, tables = load_snapshot(snapshot_path)
    assert label == "2026Q3"
    assert "a" in tables

    before = sorted(out_dir.iterdir())
    capsys.readouterr()

    code2 = main(["generate", "--dialect", "mysql", "--label", "2026Q4",
                 "--out", str(out_dir), str(new), "--old", str(snapshot_path)])
    assert code2 == 0
    out2 = capsys.readouterr().out
    assert out2.strip() == ""
    after = sorted(out_dir.iterdir())
    assert before == after


def test_generate_flyway_mit_nicht_numerischem_label_gibt_2_zurueck(tmp_path, capsys):
    new = tmp_path / "new"
    write(new / "a.sql", "CREATE TABLE a (id int)")
    out_dir = tmp_path / "out"

    code = main(["generate", "--dialect", "mysql", "--label", "2026Q3",
                "--out", str(out_dir), str(new), "--flyway"])

    assert code == 2
    err = capsys.readouterr().err
    assert err.startswith("error:")


def test_generate_out_zeigt_auf_vorhandene_datei_gibt_2_zurueck(tmp_path, capsys):
    new = tmp_path / "new"
    write(new / "a.sql", "CREATE TABLE a (id int)")
    out_path = tmp_path / "out"
    write(out_path, "das hier ist eine Datei, kein Verzeichnis")

    code = main(["generate", "--dialect", "mysql", "--label", "2026Q3",
                "--out", str(out_path), str(new)])

    assert code == 2
    err = capsys.readouterr().err
    assert err.startswith("error:")


def test_generate_mit_kritischer_aenderung_warnt_auf_stderr_rc_bleibt_0(tmp_path, capsys):
    old = tmp_path / "old"
    new = tmp_path / "new"
    write(old / "a.sql", "CREATE TABLE a (id int, weg int)")
    write(new / "a.sql", "CREATE TABLE a (id int)")
    out_dir = tmp_path / "out"

    code = main(["generate", "--dialect", "mysql", "--label", "2026Q3",
                "--out", str(out_dir), "--old", str(old), str(new)])

    assert code == 0
    err = capsys.readouterr().err
    assert "1 critical table(s) fused - review required" in err


# ---- baseline -----------------------------------------------------------------

def test_baseline_ueber_zwei_tabellen_schreibt_zwei_ausfuehrbare_dateien(tmp_path, capsys):
    new = tmp_path / "new"
    write(new / "a.sql", "CREATE TABLE a (id int)")
    write(new / "b.sql", "CREATE TABLE b (id int)")
    out_dir = tmp_path / "out"

    code = main(["baseline", "--dialect", "mysql", "--label", "1",
                "--out", str(out_dir), str(new)])

    assert code == 0
    files = sorted(out_dir.glob("V1.*.sql"))
    assert len(files) == 2
    for path in files:
        content = path.read_text(encoding="utf-8")
        assert "SELECT 1/0" not in content


# ---- Fehlerfaelle -----------------------------------------------------------------

def test_unbekannter_dialekt_gibt_2_zurueck(tmp_path, capsys):
    new = tmp_path / "new"
    write(new / "a.sql", "CREATE TABLE a (id int)")

    code = main(["check", "--dialect", "voellig-unbekannt", str(new), str(new)])

    assert code == 2
    err = capsys.readouterr().err
    assert err.startswith("error:")


def test_check_defektes_snapshot_ohne_label_gibt_2_zurueck(tmp_path, capsys):
    snapshot_path = tmp_path / "kaputt.json"
    write(snapshot_path, json.dumps({"ddldelta_snapshot": 1, "tables": {}}))
    new = tmp_path / "new"
    write(new / "a.sql", "CREATE TABLE a (id int)")

    code = main(["check", "--dialect", "mysql", str(snapshot_path), str(new)])

    assert code == 2
    err = capsys.readouterr().err
    assert err.startswith("error:")


def test_check_skalares_json_als_snapshot_gibt_2_zurueck(tmp_path, capsys):
    snapshot_path = tmp_path / "skalar.json"
    write(snapshot_path, "42")
    new = tmp_path / "new"
    write(new / "a.sql", "CREATE TABLE a (id int)")

    code = main(["check", "--dialect", "mysql", str(snapshot_path), str(new)])

    assert code == 2
    err = capsys.readouterr().err
    assert err.startswith("error:")


# ---- snapshot -----------------------------------------------------------------

def test_snapshot_kommando_schreibt_ladbaren_snapshot(tmp_path, capsys):
    new = tmp_path / "new"
    write(new / "a.sql", "CREATE TABLE a (id int)")
    snapshot_path = tmp_path / "out.json"

    code = main(["snapshot", "--dialect", "mysql", "--label", "2026Q3",
                "--out", str(snapshot_path), str(new)])

    assert code == 0
    label, tables = load_snapshot(snapshot_path)
    assert label == "2026Q3"
    assert "a" in tables
