import pytest

from ddldelta.errors import GenerationError
from ddldelta.model import table_from
from ddldelta.plan import build_plan
from ddldelta.policy import FusePolicy
from ddldelta.render.files import PROVENANCE_TEMPLATE, provenance, write_generated, write_plan

GERMAN = "-- generiert von {generated_by} ({comparison}); nicht manuell aendern"


# ---- provenance (default template) ---------------------------------------------

def test_default_template_ist_englisch():
    line = provenance("a -> b", "x")
    assert line == "-- generated by x (a -> b); do not edit manually"
    assert PROVENANCE_TEMPLATE.startswith("-- generated by")


def test_deutsches_template_bleibt_injizierbar_und_guard_filtert_es(tmp_path):
    target = tmp_path / "V1.0001__A.sql"
    target.write_text("-- generiert von alt (a -> b)\nSQL;\n", encoding="utf-8")
    # gleicher Fakteninhalt, nur Provenienz anders -> skip, Datei unangetastet
    assert write_generated(target, "-- generiert von neu (a -> b)\nSQL;\n",
                           provenance_template=GERMAN) is False


# ---- write_generated (exists-guard) -------------------------------------------

def test_write_generated_schreibt_neu(tmp_path):
    target = tmp_path / "V1.0001__A.sql"
    assert write_generated(target, "-- generiert von x (a -> b)\nSQL;\n")
    assert target.read_text(encoding="utf-8").endswith("SQL;\n")


def test_write_generated_identisch_wird_uebersprungen(tmp_path):
    target = tmp_path / "V1.0001__A.sql"
    content = "-- generiert von x (a -> b)\nSQL;\n"
    target.write_text(content, encoding="utf-8")
    assert write_generated(target, content) is False


def test_write_generated_altbestand_ohne_provenienz_zaehlt_als_identisch(tmp_path):
    target = tmp_path / "V1.0001__A.sql"
    target.write_text("SQL;\n", encoding="utf-8")  # deployed pre-provenance file
    assert write_generated(target, "-- generiert von x (a -> b)\nSQL;\n",
                           provenance_template=GERMAN) is False
    # the deployed file stays byte-identical (schemachange checksum!)
    assert target.read_text(encoding="utf-8") == "SQL;\n"


def test_write_generated_meta_evolution_zaehlt_als_identisch(tmp_path):
    # Deployte Datei aus der Zeit vor dem Metablock (nur "_DELIVERY"): die
    # Lieferanten-Fakten sind gleich, nur der Meta-Rahmen hat sich
    # weiterentwickelt -> skip, Datei bleibt unangetastet.
    target = tmp_path / "V1.0001__A.sql"
    old = ('CREATE TABLE "A" (\n    "id" INT NOT NULL,\n'
           '    "_DELIVERY" VARCHAR\n);\n')
    target.write_text(old, encoding="utf-8")
    new = ("-- generiert von x ((initial) -> 1)\n"
           'CREATE TABLE "A" (\n    "id" INT NOT NULL,\n'
           '    "_DELIVERY" VARCHAR,\n    "_VALID_FROM" DATE\n);\n')
    assert write_generated(target, new, provenance_template=GERMAN) is False
    assert target.read_text(encoding="utf-8") == old


def test_write_generated_fakten_drift_bricht_weiter_ab(tmp_path):
    target = tmp_path / "V1.0001__A.sql"
    target.write_text('CREATE TABLE "A" (\n    "id" INT NOT NULL\n);\n',
                      encoding="utf-8")
    with pytest.raises(GenerationError):
        write_generated(
            target, 'CREATE TABLE "A" (\n    "id" VARCHAR NOT NULL\n);\n')


def test_write_generated_abweichung_bricht_ab(tmp_path):
    target = tmp_path / "V1.0001__A.sql"
    target.write_text("ALTES SQL;\n", encoding="utf-8")
    with pytest.raises(GenerationError):
        write_generated(target, "NEUES SQL;\n")


def test_provenienz_template_ohne_statischen_anfang_wirft(tmp_path):
    target = tmp_path / "V1.0001__A.sql"
    target.write_text("SQL;\n", encoding="utf-8")
    with pytest.raises(GenerationError, match="static"):
        write_generated(target, "SQL;\n", provenance_template="{generated_by} foo")


# ---- write_plan (path containment) --------------------------------------------

def test_boesartiger_tabellenname_scheitert_beim_schreiben(tmp_path):
    # A table name is a vendor/supplier-controlled identifier - a delivered
    # DDL file naming a table "../../../evil" parses fine - so the
    # constructed migration filename must not be trusted to stay under
    # target_dir. (The fixed "V<label>.<NNNN>__" prefix absorbs exactly one
    # leading ".." harmlessly since it has no separator before the table
    # name, hence three levels here to actually clear target_dir.)
    new = {"../../../evil": table_from("../../../evil", {"id": ("INT", True)})}
    plan = build_plan("1", "(initial) -> 1", {}, new, FusePolicy())

    with pytest.raises(GenerationError, match="escaping"):
        write_plan(plan, tmp_path / "out", "test.generator")
